## Tell latexmk how to build the gitHeadInfo file
system("./gitHeadInfo.sh");

## Tell latexmk how to handle Asymptote diagrams
sub asy {return system("asy \"$_[0]\"");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");
